# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a task to record', max_length=100, verbose_name='Task name')),
                ('history', jsonfield.fields.JSONField(default={}, help_text='JSON containing the tasks history', verbose_name='history')),
            ],
            options={
                'verbose_name_plural': 'Task Histories',
                'verbose_name': 'Task History',
            },
        ),
    ]
